# Generated by Django 3.2 on 2021-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('conference_name', models.CharField(max_length=100)),
                ('paper_name', models.CharField(max_length=100, unique=True)),
                ('topics', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('co_author', models.BinaryField(max_length=1000)),
                ('abstract', models.CharField(max_length=2000)),
                ('keywords', models.BinaryField(max_length=1000)),
                ('pdf_paper', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CfpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('conference_name', models.CharField(max_length=500, unique=True)),
                ('conference_acronym', models.CharField(max_length=500, unique=True)),
                ('conference_start_date', models.DateField()),
                ('conference_end_date', models.DateField()),
                ('cfp_abstract_deadlines', models.DateField()),
                ('cfp_submission_deadline', models.DateField()),
                ('webpage', models.CharField(max_length=500)),
                ('venue', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('country_region', models.CharField(max_length=500)),
                ('primary_area', models.CharField(max_length=500)),
                ('secondary_area', models.CharField(max_length=500)),
                ('area_notes', models.CharField(max_length=500)),
                ('topic_1', models.CharField(max_length=500)),
                ('topic_2', models.CharField(max_length=500)),
                ('topic_3', models.CharField(max_length=500)),
                ('topic_4', models.CharField(max_length=500)),
                ('extra_information', models.CharField(max_length=500)),
                ('paper_assigned', models.BooleanField(default=False)),
                ('document', models.FileField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('conference_name', models.CharField(max_length=500, unique=True)),
                ('conference_acronym', models.CharField(max_length=500, unique=True)),
                ('conference_start_date', models.DateField()),
                ('conference_end_date', models.DateField()),
                ('organizer', models.CharField(max_length=500)),
                ('organizer_webpage', models.CharField(max_length=500)),
                ('webpage', models.CharField(max_length=500)),
                ('venue', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('country_region', models.CharField(max_length=500)),
                ('primary_area', models.CharField(max_length=500)),
                ('secondary_area', models.CharField(max_length=500)),
                ('area_notes', models.CharField(max_length=500)),
                ('topic_1', models.CharField(max_length=500)),
                ('topic_2', models.CharField(max_length=500)),
                ('topic_3', models.CharField(max_length=500)),
                ('topic_4', models.CharField(max_length=500)),
                ('Your_role', models.CharField(max_length=500)),
                ('extra_information', models.CharField(max_length=500)),
                ('assigned_paper', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('conference_acronym', models.CharField(max_length=500)),
                ('review', models.CharField(max_length=2000)),
                ('conference_name', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
