# Generated by Django 3.2 on 2021-05-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterlogin', '0002_cfpdata_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('conference_acronym', models.CharField(max_length=500)),
                ('Feedback', models.CharField(max_length=2000)),
                ('conference_name', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='cfpdata',
            name='Feedback',
        ),
    ]
