# Generated by Django 3.2 on 2021-05-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterlogin', '0003_auto_20210506_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='Suggest',
            field=models.CharField(default='NO', max_length=40),
        ),
    ]
