# Generated by Django 3.2 on 2021-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterlogin', '0006_auto_20210506_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordata',
            name='paper_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
