# Generated by Django 3.2 on 2021-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterlogin', '0007_authordata_paper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordata',
            name='topics',
            field=models.BinaryField(blank=True, max_length=1000),
        ),
    ]
